mm : reserve_area : fix implicit declaration caused by unmapped_area changes
../mm/reserve_area.c:63:11: error: implicit declaration of function 'unmapped_area_topdown' [-Werror,-Wimplicit-function-declaration]
                        addr = unmapped_area_topdown(&info_b);